title: 'Vue DAG'
base: '/'
serviceWorker: true
themeConfig: 
  repo: 'AlexImb/vue-dag'
  docsDir: 'docs'
  editLinks: true
  serviceWorker: 
    updatePopup: true
  nav:
    - text: Home
      link: '/'
    - text: Guide
      link: '/guide/installation'
    - text: API
      link: '/api/'
    - text: Demo
      link: 'https://vue-dag-example.netlify.app'
  sidebarDepth: 2,
  sidebar:
    - '/guide/':
      title: 'Guide'
      collapsable: false
      children: 
        - 
          - 'guide/installation'
          - 'Installation'
    - '/api/':
      title: 'API'
      collapsable: false
      children: 
        - 
          - 'api/props'
          - 'Props'
        - 
          - 'api/events'
          - 'Events'
        - 
          - 'api/slots'
          - 'Slots'
        
    